services:
  backend:
    build: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend/models:/app/models
      - ./uploads:/app/uploads
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    tty: true

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: humblehome
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  dbdata:
