name: Lint CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-frontend:
    name: Lint React Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: humblehome/frontend
        run: npm ci

      - name: Run ESLint
        working-directory: humblehome/frontend
        run: npx eslint src --max-warnings=0

  lint-backend:
    name: Lint Flask Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        working-directory: humblehome/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black

      - name: Run flake8
        working-directory: humblehome/backend
        run: flake8 .

      - name: Run black check
        working-directory: humblehome/backend
        run: black --check .