name: Test Docker Compose

on:
  push:

jobs:
  test-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          docker compose up --build -d
        working-directory: humblehome
          
      - name: Wait for docker to start up
        run: sleep 10

      - name: Test Index Page
        run: |
          curl -s -o response.html http://localhost:3000/
          grep "<title>React App</title>" response.html

      - name: Stop Docker Containers
        run: docker compose down 
        working-directory: humblehome


  dependency-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "humblehome_main_branch"
          path: "humblehome"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: dependency-check-report
