jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and run your app containers
      - name: Build and start app services
        run: docker compose up -d
        working-directory: humblehome

      # Wait for your app to be ready (Nginx etc)
      - name: Wait for app to be up
        run: curl --retry 10 --retry-connrefused --retry-delay 3 http://localhost

      # Install python deps
      - name: Setup python and install deps
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install -r humblehome/backend/requirements.txt
      - run: pip install chromedriver-autoinstaller

      # Run your Selenium test, which must connect to 'selenium:4444'!
      - name: Run Selenium UI Test
        working-directory: humblehome/backend
        run: python tests/selenium/ui_test.py
